# Generated by Django 6.0.2 on 2026-02-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rasgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animales/')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('historia', models.TextField()),
                ('estado', models.CharField(choices=[('ADOPCION', 'En Adopción'), ('REHAB', 'En Rehabilitación'), ('ADOPTADO', 'Adoptado')], default='ADOPCION', max_length=10)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='refugio.especie')),
                ('rasgos', models.ManyToManyField(blank=True, to='refugio.rasgo')),
            ],
        ),
    ]
