# Generated by Django 6.0.2 on 2026-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0002_solicitudadopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='experiencia_previa',
            field=models.BooleanField(default=False, verbose_name='¿Tienes experiencia previa?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='tipo_vivienda',
            field=models.CharField(choices=[('PISO', 'Piso / Apartamento'), ('CASA', 'Casa con jardín / Adosado'), ('FINCA', 'Finca / Terreno rústico')], default='PISO', max_length=20),
        ),
    ]
