# Generated by Django 6.0.2 on 2026-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugio', '0003_solicitudadopcion_experiencia_previa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='horas_solitario',
            field=models.IntegerField(default=0, help_text='¿Cuántas horas al día pasará solo?'),
        ),
        migrations.AddField(
            model_name='solicitudadopcion',
            name='otras_mascotas',
            field=models.BooleanField(default=False, verbose_name='¿Tienes otras mascotas?'),
        ),
    ]
